### ISSUE TITLE
DUPLICATE Sync assisted installer storage documented requirements and validations

### ISSUE THREAD

**Issue by jhernand** [open-cluster-management/rhacm-docs#4372] opened 2022-11-22 17:06 UTC
## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

* https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html-single/multicluster_engine/index#enable-cim

## What are the suggested changes?

The sizes required for the assisted installer storage areas are not in sync with what the service itself validates:

| Area | Documented | Validated |
| - | - | - |
| Database | - | 1G |
| Filesystem | 100G | 1G |
| Images | 50G | 10G |

The validations were introduced here:

 * Ticket -  https://issues.redhat.com/browse/MGMT-11700
 * Patch - https://github.com/openshift/assisted-service/pull/4463

We should sync both things, but not sure if we should decrease the requirements in the documentation or increase them in the validations.

**Comment by jhernand** [comment] 2022-11-22 17:06
Part of the solution, for the database storage, is in #4371.

**Comment by oafischer** [comment] 2022-11-23 14:59
@jelkosz Can you chime in on this?

**Comment by jelkosz** [comment] 2022-11-23 15:20
well, I see that as a difference between minimal sizes and recommended sizes. So I dont see a problem that the documentation recommends something more than the validated minimal sizes.

@filanov WDYT?

**Comment by filanov** [comment] 2022-11-24 09:00
I agree we should recommend more then the minimum.
I suggest to document both the recommended and the minimum.

**Comment by swopebe** [comment] 2022-11-28 17:22
This is not where we should be opening doc issues. I am closing this and opening in the backlog. Feel free to open a JIRA issue next time if you cannot access the backlog. 

duplicate of https://github.com/stolostron/backlog/issues/26935

**Closed as completed** 2022-11-28 17:34 UTC
Labels: duplicate, squad:doc
